### ISSUE TITLE
方案名太长，能否缩短

### ISSUE THREAD

**Issue by laubonghaudoi** [safetychinese/rime-jutjnyu_gaulaupin_dangjunbikwaa#2]
目前`rime-jutjnyu_gaulaupin_dangjunbikwaa`这个方案id太长，不利于输入法程序识别和整理，能否改为更短的方案名，例如本repo改名为`gaulau_jyutping`，其中藤县白话方案id改为`gaulau_jyutping_dangjun`。

**Comment by cryptogun** [comment]
没问题，刘邦后代 😆 
我这里估计几年才有一次问津~
周末有空再弄吧

**Comment by laubonghaudoi** [comment]
谢谢，我觉得README可以修改一下，例如教程部分直接参考我的[博客](https://laubonghaudoi.github.io/dialects/)（给自己打广告了）。还有忍不住吐槽缺陷里面的““经常使用本方案输入，可能会导致普通话生疏、不标准。”另外声韵母和声调介绍可以参照这个[南宁白话拼音方案](https://leimaau.github.io/book/PHONETICIZE.html)写得更清晰一些。一些意见仅供参考。

**Comment by cryptogun** [comment]
工作了不像学生时代那么有闲啦。一点想法：
1. readme确实是语言组织能力太差，有空再改吧。
1. 教程的话，你那个也是很繁琐，主要是因为Rime缺少一键配置工具。
想普及，想适合大众使用，最好能够达到即装即用。或者能够在2、3步之内配置好。还得配上截图。  
步骤太多只能沦为小众的玩意。
1. 缺陷保留，这是使用过2个月之后的亲身体验~
卷舌音不会发、普通话不好的烦恼很多南方人都可能有。更别说用了母语输入法之后了。拼音几天不用就会生疏，说普通话时是得多花精力和注意。这个缺点说一下没坏处的。  
1. 对于输入方案来说，Jyutping方案还是不够理想。对于语言研究来说那就挺完美的，语音语素什么的都不缺。
- 拼音经常太长，比如粤语的`ngaang 硬`
- 跟普通话发音冲突 `ang` `eng` `ong` `ai`分别对应普通话的`eng` `iang` `∅` `ei`
- 明明是`啊`: a，偏偏要按2次:`aa`
- 明明有`y`却用`j`代替
语言就是个工具

**Comment by cryptogun** [comment]
抱歉不小心关闭issue了，`Ctrl+Shift+Enter`居然是”提交评论并关闭issue“的机能。在Sublime里这个快捷键代表”在上面插入空行“。

工作了不像学生时代那么有闲啦。一点想法：
1. readme确实是语言组织能力太差，有空再改吧。
1. 教程的话，你那个也是很繁琐，主要是因为Rime缺少一键配置工具。
想普及，想适合大众使用，最好能够达到即装即用。或者能够在2、3步之内配置好。还得配上截图。  
步骤太多只能沦为小众的玩意。
1. 缺陷保留，这是使用过2个月之后的亲身体验~
卷舌音不会发、普通话不好的烦恼很多南方人都可能有。更别说用了母语输入法之后了。拼音几天不用就会生疏，说普通话时是得多花精力和注意。这个缺点说一下没坏处的。  
1. 对于输入方案来说，Jyutping方案还是不够理想。对于语言研究来说那就挺完美的，语音语素什么的都不缺。
- 拼音经常太长，比如粤语的`ngaang 硬`
- 跟普通话发音冲突 `ang` `eng` `ong` `ai`分别对应普通话的`eng` `iang` `∅` `ei`
- 明明是`啊`: a，偏偏要按2次:`aa`
- 明明有`y`却用`j`代替
  
我一直在想要不要设计一个基于普通话拼音的输入方案，用户从其他输入法过来的话，过渡自然不违和。然后不继续维护这个repo了。开源项目就类似接力棒，谁脑子一热时间一多都可以来推进一把。  
语言就是个工具，输入法也要以舒适和实用为主。我觉得嘛，大家都是一个语族，共同性更多，不用特意强调差异性。

**Comment by laubonghaudoi** [comment]
没办法，我那个教程写那么长就是因为本身步骤就很复杂，如果写得不详细用户用不了的话，反而更麻烦。这个教程本身就是个过渡期产物，我之前也联系过几个平台输入法的作者，请求他们尽快支持方案一键下载部署功能，但大家都是业余做这个项目所以进度很慢。我目前的工作是联系各个方案作者将自己的方案开源到GitHub上将其配方化，这样至少小狼毫能一键下载方案，iRime也能比较方便的直接点击下载。

至于粤拼的设计，用aa是因为粤语本身就有[ɐ]和[a]的对立。如果用a来表示[a]，例如耶鲁方案，则容易造成混淆，不易记忆使用。而用j来表示[j]则是直接遵循IPA设计，同样粤拼中的y也即是[y]。基于普通话拼音的方案其实前人已有大量探索，正是因为效果不理想，所以才需要另起炉灶（粤语可以参考那本饶秉才的广州音字典，用的就是普通话拼音改造过来的方案）。拼音方案的设计首要考虑准确性和内部一致性，能准确反映语言的音位对立。普通话拼音本身也有一些问题，例如bo和hui实际上代表的是buo和huei的音（至今也有很多人不知道这是个省略写法）。而因为普通话音系和其他汉语音系差异过大，所以汉语族内所有拼音方案都基于普通话拼音来设计是不现实的。官话区内的拼音方案则没有问题，例如我项目中收录的蜀拼和南京话拼音方案，还有正在制作中的湖北话方案，都基于普通拼音方案设计。但别的汉语例如吴语中的清浊对立，粤语中的[ɐ][a]对立，沿用普通话拼音设计就明显不科学了。

我非常同意让大众来共同维护一个拼音方案项目，当然前提是有一个主要负责人来检查每次pull request的修改。单由一个人来维护更新方案很难做到实时更新，利用开源的力量来改进方案会更高效。

关于方案设计的问题，我目前在考虑综合各个方案作者的经验，总结出一份拼音方案设计的指南或参考标准，不过该设想仍停留在构思阶段，最近也比较忙没时间推进。

**Comment by cryptogun** [comment]
好了，新repo在这： https://github.com/cryptogun/gaulau_jyutping
你看行的话我就关闭这个issue啦。

嗯，一键部署看到了你们在这里讨论： https://github.com/rime/weasel/issues/300

谢谢提示哈，耶鲁方案接近拼音那有空我看看。程序员原则就是不要重复造轮子。方案设计急不来的，否则可能会留下一大堆deprecated repo。

**Comment by laubonghaudoi** [comment]
感谢，不过其实无需新开一个repo，直接把这个rename就行了……更新方案不需要deprecate repo，只要这个repo名称不变，且保证每次提交都经过测试，输入法每次抓取的方案就会是可用的方案。

关于一键部署方案功能，其实有个更新更全面的讨论，就是这个[#336](https://github.com/rime/home/issues/336)我在里面总结出了一份方案管理逻辑的流程图，尚不知道几位大佬的意见如何。

关于拼音方案设计，其实有一种原则，就是先为每个语言的标准音设计一套方案，然后其他片区的方音以此为基准做修改。例如我所收集到的南宁粤拼即基于粤拼修改，同理蜀拼和南京话拼音也由普通话拼音修改而成，吴语学堂方案则是以台州话为基准音直接做出了兼容多地方音的方案。粤语区最好还是以粤拼为基础来修改兼容多地方音。

**Comment by cryptogun** [comment]
rename没试过。重命名那原来的引用旧名字的链接不就都失效了？比如[这个](https://github.com/osfans/rime-tool)
那还是改这个repo吧，repo多了会让人混淆。

**Comment by cryptogun** [comment]
嗯，改好了。有问题可以再开这个issue哈。

**Comment by laubonghaudoi** [comment]
重命名不会导致原来链接失效，就例如我的收集项目，虽然已改名为Chinese_rime，但即使是用[Chinese_dialect_rime_schema](https://github.com/laubonghaudoi/Chinese_dialect_Rime_schema)还是能重定向至仓库。除非新建一个同名仓库，否则用过的仓库名称都会自动重定向至当前仓库。
